### ISSUE TITLE
Parrot_run_callback uses void* to pass arbitrary data

### ISSUE THREAD

**Issue by gerdr** [parrot/parrot#742]
The `external_data` argument of `Parrot_run_callback()` has type `void*`, but is also used to pass integers of various types.

With the increased warning levels, this breaks the g++ build on win64 (strawberry-perl-5.14.2.1, gcc 4.4.7):

```
src/interp/inter_cb.c: In function 'void Parrot_run_callback(parrot_interp_t*, PMC*, void*)':
src/interp/inter_cb.c:317: error: cast from 'void*' to 'long int' loses precision
src/interp/inter_cb.c:320: error: cast from 'void*' to 'long int' loses precision
src/interp/inter_cb.c:323: error: cast from 'void*' to 'long int' loses precision
src/interp/inter_cb.c:326: error: cast from 'void*' to 'long int' loses precision
```

I'll add a temporary fix for that (together with some other failures I've come accross), but long-term we really should use a union here...
